### ISSUE TITLE
Evicted libraries incorrectly included in report

### ISSUE THREAD

**Issue by benmccann** [sbt/sbt-license-report#10]
I'm seeing lots of duplicate libraries in my report. E.g.

>none specified 	 	com.google.http-client # google-http-client # 1.19.0
none specified 	 	com.google.http-client # google-http-client # 1.20.0 

It doesn't seem necessary to included evicted libraries in the license report since they're not actually being used. In this case we could just include 1.20.0

**Comment by jsuereth** [comment]
good call, will fix
