### ISSUE TITLE
Add a "Proprietary" `LicenseCategory`

### ISSUE THREAD

**Issue by metasim** [sbt/sbt-license-report#18]
Would be nice to have a standardized means of marking a license as non-permissive.

**Comment by metasim** [comment]
Let me know if this idea is agreeable and I can issue a PR.

**Comment by mdedetrich** [comment]
@eed3si9n I believe this can be closed since it already exists (see https://github.com/sbt/sbt-license-report/blob/0f3b261dccea0509bc89d9cf9adcff49089748f6/src/main/scala/sbtlicensereport/license/LicenseCategory.scala#L34)
