### ISSUE TITLE
Add support for Eclipse Public License (EPL) `LicenseCategory`.

### ISSUE THREAD

**Issue by metasim** [sbt/sbt-license-report#19]

**Comment by xuwei-k** [comment]
- https://github.com/sbt/sbt-license-report/pull/58
- https://github.com/sbt/sbt-license-report/pull/22
- https://github.com/sbt/sbt-license-report/blob/00e05d888acfcf1c71c1ffe1c4956995c0dfb322/src/main/scala/sbtlicensereport/license/LicenseCategory.scala#L39

**Comment by eed3si9n** [comment]
Closing this.
