### ISSUE TITLE
Cut new release

### ISSUE THREAD

**Issue by benmccann** [sbt/sbt-license-report#27]
There's been a few fixes recently. It'd be good to cut a new release after https://github.com/sbt/sbt-license-report/pull/26 is merged

**Comment by benmccann** [comment]
@eed3si9n @jsuereth would either of you be able to cut a new release for this?

**Comment by mkurz** [comment]
@benmccann A new release is out.
BTW: Did you know that running `dependencyLicenseInfo` from https://github.com/jrudolph/sbt-dependency-graph gives you a similiar result?

**Comment by benmccann** [comment]
Yay, yay!! Thank you @dwijnand !

@mkurz I did not know sbt-dependency-graph would do that for you! I am curious to test it and see if it gives the same results. I'm guessing it probably needs SBT 0.13.11 to output the correct results just like this plugin does, but will be curious to see

**Comment by mkurz** [comment]
@benmccann @dwijnand I think you can close this issue.
