### ISSUE TITLE
Licenses resulting from test dependencies should be marked as such

### ISSUE THREAD

**Issue by Sciss** [sbt/sbt-license-report#30]
It appears to me that the report does not distinguish between licenses for main dependencies and test dependencies. I believe it's perfectly valid for example to have a project whose test dependencies contain a library licensed under GPL without requiring the project to be covered by GPL, because neither test sources nor test binaries are published. I therefore suggest to either mark licenses that result from test dependencies or simply to remove them.

**Comment by ant8e** [comment]
By default the report contains dependencies from the "compile" and "test" ivy configurations.

If you wish to only output the dependencies in the "compile" configuration you can  set
`licenseConfigurations := Set("compile")`

**Comment by Sciss** [comment]
Ok, thanks; I guess the issue can then be closed
