### ISSUE TITLE
Parent POM License

### ISSUE THREAD

**Issue by jamesward** [sbt/sbt-license-report#34]
Some artifacts specify their license in their parent POM.  That information should propagate.

**Comment by jamesward** [comment]
Here is an example artifact that uses a parent POM to specify the license:
https://search.maven.org/#artifactdetails%7Cxalan%7Cserializer%7C2.7.2%7Cjar

The parent:
https://search.maven.org/#artifactdetails%7Corg.apache%7Capache%7C4%7Cpom

**Comment by benmccann** [comment]
This has been fixed. It was a bug in sbt's ivy implementation. The README for this project is out-of-date though. Documentation fix here: https://github.com/sbt/sbt-license-report/pull/37

**Comment by jamesward** [comment]
Thanks!
