### ISSUE TITLE
cross build for sbt 1.0

### ISSUE THREAD

**Issue by xuwei-k** [sbt/sbt-license-report#35]

**Comment by aumann** [comment]
Has this already been published? I seem to be unable to use the plugin with sbt 1.0 - using version 1.2.0 as described in the docs.

**Comment by eed3si9n** [comment]
Not yet. We'll push it out soon.

**Comment by liff** [comment]
Can you publish this or is there something preventing it?

**Comment by eed3si9n** [comment]
Sorry it took so long. It's out!

https://bintray.com/sbt/sbt-plugin-releases/sbt-license-report/1.2.0#files/com.typesafe.sbt%2Fsbt-license-report%2Fscala_2.12%2Fsbt_1.0%2F1.2.0%2Fjars
