### ISSUE TITLE
Scala2.13

### ISSUE THREAD

**Issue by tockri** [sbt/sbt-license-report#45]
Thank you for great product!
Recently we've upgraded Scala version of our product to 2.13, then sbt-license-report fails on
```
sbt.librarymanagement.ResolveException: Error downloading com.typesafe.sbt:sbt-license-report;sbtVersion=1.0;scalaVersion=2.
13:1.2.0
 :
not found: https://repo1.maven.org/maven2/com/typesafe/sbt/sbt-license-report_2.13_1.0/1.2.0/sbt-license-report-1.2.0.pom
 :
```

Do you have some plans to support scala 2.13 in your product?
Thanks,

**Comment by mkurz** [comment]
sbt 1 is using Scala 2.12. There is not need to release this library for Scala 2.13.
Where did you define the sbt-license-report dependency? You have to put it into `project/plugins.sbt` (or `project/license.sbt`, the filename does not matter as long it's a `.sbt` file in the `project` folder).

**Comment by tockri** [comment]
Oh thanks @mkurz , I found the cause, I wrongly placed my license-report.sbt in my `$HOME/.sbt/1.0` intead of `$HOME/.sbt/1.0/plugins`. 😓 
I moved it to `plugins` directory then now it's working perfectly.
