### ISSUE TITLE
artifact no longer found

### ISSUE THREAD

**Issue by Sciss** [sbt/sbt-license-report#49]
hi there,

current sbt cannot locate the plugin after bintray shutdown:

```
[error] Error downloading com.typesafe.sbt:sbt-license-report;sbtVersion=1.0;scalaVersion=2.12:1.2.0
[error]   Not found
[error]   Not found
[error]   not found: ~/.ivy2/local/com.typesafe.sbt/sbt-license-report/scala_2.12/sbt_1.0/1.2.0/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/typesafe/sbt/sbt-license-report_2.12_1.0/1.2.0/sbt-license-report-1.2.0.pom
```

can you publish to sonatype, or is there an alternative resolver?

**Comment by eed3si9n** [comment]
https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-license-report/scala_2.12/sbt_1.0/1.2.0/, which should be part of the default resolver should still resolve.

**Comment by Sciss** [comment]
hmmm, I'm getting the above error from bloop, but the entire build system is opaque to me, and I gave up trying to understand what is going on. I guess as you write, it should be found "normally"

**Comment by radeusgd** [comment]
> [repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-license-report/scala_2.12/sbt_1.0/1.2.0](https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-license-report/scala_2.12/sbt_1.0/1.2.0/), which should be part of the default resolver should still resolve.

It was resolving, until [today when the repo went down](https://github.com/sbt/sbt/issues/7202).

Hopefully, the repo will be up soon, but would it be maybe possible to publish the plugin to Maven Central? This way it would have better redundancy. I think many sbt plugins are in Maven central, since during this repo failure only this plugin seems to be affecting us. Any chance it could be updated?

**Comment by mkurz** [comment]
This repo finally needs to be migrated to the `com.github.sbt` groupid with sbt-ci-release set up. I can do the ci-release setup part, however @eed3si9n or @SethTisue can you add the secrets?

**Comment by eed3si9n** [comment]
Sure. Created an issue for this #51.
