### ISSUE TITLE
Migrated to the `com.github.sbt` organization

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt-license-report#51]
This repo finally needs to be migrated to the `com.github.sbt` groupid with sbt-ci-release set up. I can do the ci-release setup part, however @eed3si9n or @SethTisue can you add the secrets?

_Originally posted by @mkurz in https://github.com/sbt/sbt-license-report/issues/49#issuecomment-1500406134_

**Comment by eed3si9n** [comment]
Sounds good to me.

**Comment by mkurz** [comment]
For the record: https://github.com/scala-steward-org/scala-steward/pull/3027
