### ISSUE TITLE
Problems resolving license information from parent POM

### ISSUE THREAD

**Issue by obfischer** [sbt/sbt-license-report#7]
Using version 1.0.0 of sbt-license-report it seems to have an issue with resolving license information set in the parent POM of a project. For many Apache projects sbt-license-report is unable to determine the license of the project. A good example is Apache Commons IO (https://repo1.maven.org/maven2/commons-io/commons-io/2.4/commons-io-2.4.pom). The POM of Commons IO relies on the license information provided by the parent POM but is reported as not specified by sbt-license-report.

So, it would be great if sbt-license-report would be able to use also licence information provided by a parent POM.

**Comment by benmccann** [comment]
+1  this is the case for about 50% of libraries I include

Here are a couple examples:

    io.dropwizard.metrics # metrics-json # 3.1.1 
    com.fasterxml.jackson.core # jackson-databind # 2.5.3

**Comment by sjbog** [comment]
I've traced the bug to PomModuleDescriptorParser#parseDescriptor method of the Apache Ivy library. They set only current pom (domReader) file's licenses, without parent's (although the parent is being parsed as well).
Line 167: `mdBuilder.setLicenses(domReader.getLicenses());`
Need to create issue in their Jira.

**Comment by benmccann** [comment]
Awesome, glad you were able to track it down. I filed an issue in their JIRA https://issues.apache.org/jira/browse/IVY-1526

**Comment by benmccann** [comment]
@obfischer @sjbog @jsuereth do you know where the Apache Ivy library is being included? I don't see where it is. I'm curious what version is currently being used and what line we'd have to edit to test a fixed version, but don't see any dependencies besides commons-lang3

**Comment by benmccann** [comment]
I sent a PR will make it easy to write a test case for this - https://github.com/sbt/sbt-license-report/pull/12

**Comment by obfischer** [comment]
@benmccann Thanks for your support.

**Comment by benmccann** [comment]
I think we could implement this by calling `desc.getInheritedDescriptors.getParentMd.getLicenses` in `LicenseReport.pickLicenseForDep`

**Comment by benmccann** [comment]
Hmmm. `desc.getInheritedDescriptors` is returning an empty array. Does anyone know how to get the parent?

**Comment by benmccann** [comment]
If I look in `.ivy2/cache/com.fasterxml.jackson.core/jackson-databind/ivy-2.5.4.xml.original` then I see a reference to the parent, but when I look in `.ivy2/cache/com.fasterxml.jackson.core/jackson-databind/ivy-2.5.4.xml` then I don't. It appears that Ivy is discarding this info (or at least [SBT's fork of Ivy](https://github.com/sbt/ivy) is)

**Comment by benmccann** [comment]
This behavior seems to be the same with the upstream ivy even with 2.4.0

**Comment by benmccann** [comment]
To fix this we may have to stop using ivy and use aether which SBT 0.13.8 makes available

**Comment by jsuereth** [comment]
@benmccann We can also issue a fix in sbt/ivy, as we run our own branch.

Have you tried with the sbt-maven-resolver plugin to see if the Aether integration does fix the issue?

**Comment by benmccann** [comment]
sbt-maven-resolver seems to use the pom directly (I see ~/.ivy2/maven-cache/com/fasterxml/jackson/core/jackson-databind/2.5.4/jackson-databind-2.5.4.pom, but no corresponding ivy file), so that would fix the issue. The issue here is that when ivy converts the pom to an ivy file it drops the information regarding the parent. Rewriting this plugin to use Aether would be a lot of work, however.

I'm not sure why Ivy drops the parent info and whether this is a bug, a feature they never got around to implementing, or something they didn't implement on purpose. It does seem to know about the parent since it downloads it. But I'm not sure how to discover it and get a reference to it in this plugin since there's no reference to the parent in the ivy descriptor that's being used.

**Comment by benmccann** [comment]
There's a PR for this fix in the Ivy project. We'll need to port the fix to SBT's Ivy fork. See https://github.com/apache/ant-ivy/pull/7

**Comment by benmccann** [comment]
I filed an issue with SBT since this will need to be fixed there. See https://github.com/sbt/sbt/issues/2118

**Comment by sslavic** [comment]
sbt/sbt#2118 is fixed. Does this issue depend on something more or can it be fixed/resolved now?

**Comment by benmccann** [comment]
This will depend on  SBT 0.13.10 or SBT 1.0 being released. Once that happens I'd like to add some scripted tests here to ensure the problem is fixed. I was leaving this bug open to track confirming that the issue is indeed fixed and adding the corresponding tests
